import type { Metadata } from "next";
import "@/app/ui/globals.css";
import { Roobert } from '@/app/ui/fonts/font'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Roobert.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
